/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import ConexionSql.ConexionSQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author r9lon
 */
public class DashBoardNew extends javax.swing.JInternalFrame {
    
    ConexionSQL cc= new ConexionSQL();
    Connection con =cc.conexion();
    /**
     * Creates new form DashBoardNew
     */
    public DashBoardNew() {
        initComponents();
        recuperaDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDashboard = new javax.swing.JTable();

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("PORCENTAJE DE LLAMADAS");

        jTableDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "null", "null", "null", "null"
            }
        ));
        jScrollPane1.setViewportView(jTableDashboard);
        if (jTableDashboard.getColumnModel().getColumnCount() > 0) {
            jTableDashboard.getColumnModel().getColumn(0).setMinWidth(500);
            jTableDashboard.getColumnModel().getColumn(0).setMaxWidth(600);
            jTableDashboard.getColumnModel().getColumn(1).setResizable(false);
            jTableDashboard.getColumnModel().getColumn(2).setResizable(false);
            jTableDashboard.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDashboard;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void recuperaDatos() {
        
        
        String [] titulos= {"Tipo de llamada","Cantidad de Llamadas", "Porcentaje %"};
        String [] registros= new String[3];
        DefaultTableModel modelo= new DefaultTableModel(null, titulos);

         try {   
            
             Statement st= con.createStatement();
            ResultSet rs=st.executeQuery("CALL porcentaje_llamada();");
             
             
            while (rs.next()){
                
                registros [0]=rs.getString("tipo_llamada");
                registros [1]=rs.getString("Cantidad");
                registros [2]=rs.getString("Porcentaje");
                
                modelo.addRow(registros);
            }
            
            jTableDashboard.setModel(modelo);
            
            TableColumnModel columnModel = jTableDashboard.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(200 );
          
            } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"no se ha podido subir los datos a la tabla de Dashboard" + e.getMessage());
            }
    }

}

