/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ConexionSql.ConexionSQL;
import crudpinguino.Cliente;
import crudpinguino.Incidencias;
import crudpinguino.Telefonos;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc
 */
public class SistemaVentana extends javax.swing.JFrame {
    
    ConexionSQL cc= new ConexionSQL();
    Connection con =cc.conexion();
    
    

    
    public SistemaVentana() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(java.awt.Color.LIGHT_GRAY);
        mostrarDatos();
        jButtonSaveTel.setVisible(false);
       
        
    }
    
    //variable para añadir telefonos
    public String anadir="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTipoLlamada = new javax.swing.JLabel();
        jComboBoxTipoLlamada = new javax.swing.JComboBox<>();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaComentarios = new javax.swing.JTextArea();
        jLabelComentarios = new javax.swing.JLabel();
        jButtonaAnadirTelefono = new javax.swing.JButton();
        jButtonRegistraLlamada = new javax.swing.JButton();
        jLabelTeamBike = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jButtonSaveTel = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelCodCliente = new javax.swing.JLabel();
        jTextFieldCodCliente = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombreCom = new javax.swing.JLabel();
        jTextFieldNombreComercial = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelContacto = new javax.swing.JLabel();
        jTextFieldContacto = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabelBusqueda = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLlamadas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTOR LLAMADAS - PINGUINO");
        setBackground(new java.awt.Color(153, 255, 255));
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("CRM - GESTOR LLAMADAS");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 491, 10));

        jLabelTipoLlamada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoLlamada.setText("Tipo de Llamada:");
        jPanel1.add(jLabelTipoLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jComboBoxTipoLlamada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONSULTA B2B", "CONSULTA TALLER", "CONSULTA STOCK", "CONSULTA LOGISTICA" }));
        jPanel1.add(jComboBoxTipoLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 165, -1));

        jButtonNuevo.setBackground(new java.awt.Color(51, 153, 255));
        jButtonNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNuevo.setText("X");
        jButtonNuevo.setBorder(null);
        jButtonNuevo.setBorderPainted(false);
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 50, 30));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 99, -1));

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 99, -1));

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 181, 99, -1));

        jTextAreaComentarios.setColumns(20);
        jTextAreaComentarios.setLineWrap(true);
        jTextAreaComentarios.setRows(5);
        jTextAreaComentarios.setWrapStyleWord(true);
        jTextAreaComentarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaComentariosKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaComentarios);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 277, 130));

        jLabelComentarios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComentarios.setText("Comentarios:");
        jPanel1.add(jLabelComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jButtonaAnadirTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonaAnadirTelefono.setText("...");
        jButtonaAnadirTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaAnadirTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonaAnadirTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jButtonRegistraLlamada.setText("Registrar Llamada");
        jButtonRegistraLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistraLlamadaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistraLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, -1, -1));

        jLabelTeamBike.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTeamBike.setText("TEAM BIKE S.L.  - ");
        jPanel1.add(jLabelTeamBike, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("nunununu");
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, -1));

        jButtonSaveTel.setText("Añadir telefono");
        jButtonSaveTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveTelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaveTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_penguin_32px_1.png"))); // NOI18N
        jPanel1.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new java.awt.GridLayout(6, 2, -100, 20));

        jLabelCodCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodCliente.setText("Cod Cliente:");
        jPanel3.add(jLabelCodCliente);
        jPanel3.add(jTextFieldCodCliente);

        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jPanel3.add(jLabelNombre);
        jPanel3.add(jTextFieldNombre);

        jLabelNombreCom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreCom.setText("Nombre Com:");
        jPanel3.add(jLabelNombreCom);
        jPanel3.add(jTextFieldNombreComercial);

        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono:");
        jPanel3.add(jLabelTelefono);
        jPanel3.add(jTextFieldTelefono);

        jLabelContacto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContacto.setText("Contacto:");
        jPanel3.add(jLabelContacto);
        jPanel3.add(jTextFieldContacto);

        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email:");
        jPanel3.add(jLabelEmail);
        jPanel3.add(jTextFieldEmail);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 360, 300));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 392, 480, 10));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClientes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableClientes.setRowHeight(22);
        jTableClientes.setSelectionBackground(new java.awt.Color(255, 99, 71));
        jTableClientes.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableClientes.setShowVerticalLines(false);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jLabelBusqueda.setText("Busqueda:");

        jTextFieldBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBusquedaActionPerformed(evt);
            }
        });
        jTextFieldBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBusquedaKeyReleased(evt);
            }
        });

        jTableLlamadas = new JTable()
        {
            public boolean isCellEditable(int row, int column)
            {

                for (int i=0; i < jTableLlamadas.getRowCount(); i++)
                {
                    if (row==i)
                    {
                        return false;
                    }

                }
                return true;

            }
        };
        jTableLlamadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableLlamadas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableLlamadas.setRowHeight(22);
        jTableLlamadas.setSelectionBackground(new java.awt.Color(255, 99, 71));
        jTableLlamadas.setSelectionForeground(new java.awt.Color(255, 255, 254));
        jTableLlamadas.setShowGrid(false);
        jTableLlamadas.setShowHorizontalLines(true);
        jTableLlamadas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableLlamadasFocusGained(evt);
            }
        });
        jTableLlamadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLlamadasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableLlamadas);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabelBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBusqueda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBusquedaActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        // Accion al seleccionar un cliente
        
        limpiarCajas();
            int filaSeleccionada=jTableClientes.rowAtPoint(evt.getPoint());
        
          jTextFieldCodCliente.setText(jTableClientes.getValueAt(filaSeleccionada, 0).toString());
          jTextFieldNombre.setText(jTableClientes.getValueAt(filaSeleccionada, 1).toString());
          jTextFieldNombreComercial.setText(jTableClientes.getValueAt(filaSeleccionada, 2).toString());
          jTextFieldTelefono.setText(jTableClientes.getValueAt(filaSeleccionada, 3).toString());
          jTextFieldContacto.setText(jTableClientes.getValueAt(filaSeleccionada, 4).toString());
          jTextFieldEmail.setText(jTableClientes.getValueAt(filaSeleccionada, 5).toString());
          
          
        mostrarLlamadas();  
        //Al seleccionar una línea limpia la caja de busqueda
        jTextFieldBusqueda.setText("");
      
        
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jTextFieldBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaKeyReleased
        filtrarDatos(jTextFieldBusqueda.getText());
        
        
    }//GEN-LAST:event_jTextFieldBusquedaKeyReleased

    private void jButtonaAnadirTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaAnadirTelefonoActionPerformed
        if(jTextFieldCodCliente.getText().isEmpty() || jTextFieldNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Selecciona un cliente para esta función!");
        }
        else{
            limpiarCajasTelefono();
        }
        
        
        
        
    }//GEN-LAST:event_jButtonaAnadirTelefonoActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed

        if(jTextFieldCodCliente.getText().isEmpty() || jTextFieldNombre.getText().isEmpty() ){
            
            JOptionPane.showMessageDialog(this,"Es necesario seleccionar un cliente.");
        }
        else{
            
            actualizarDatos(jTextFieldCodCliente.getText());
            actualizarTelefono();
            limpiarCajas();
            mostrarDatos();
            
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        //boton de eliminar
        
        if(jTextFieldCodCliente.getText().isEmpty() || jTextFieldNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Es necesario seleccionar un cliente.");
        }
        else{
        
        int ventanaYesNotCancel = JOptionPane.showConfirmDialog(this, "¿Quieres eliminar este registro?", "Atención!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //0=yes, 1=no, 2=cancel
        if(ventanaYesNotCancel == 0) {
            eliminarRegistros();
            limpiarCajas();
            mostrarDatos();
            System.out.println("Has pulsado Yes");
        }else if(ventanaYesNotCancel == 1){
            System.out.println("Has pulsado No");

        }
       }

        

        // Saving code here

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        //boton de guardar

        if(jTextFieldCodCliente.getText().isEmpty() || jTextFieldNombre.getText().isEmpty() ){
            
            JOptionPane.showMessageDialog(this,"Campos requeridos: Codigo de cliente y Nombre");
        }
        else{
            insertarDatos();
            anadirTelefono();
            limpiarCajas();
            mostrarDatos();
            
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        //boton para limpiar las cajas
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jTextAreaComentariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaComentariosKeyTyped
        
       
        // Limitar text area
        if(jTextAreaComentarios.getText().length()>=200){
            evt.consume();
        }
        
    }//GEN-LAST:event_jTextAreaComentariosKeyTyped

    private void jButtonRegistraLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistraLlamadaActionPerformed
        // TODO add your handling code here:
       if(jTextFieldCodCliente.getText().isEmpty() || jTextFieldNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Es necesario seleccionar un cliente.");
        }
        else{
        
        registroLlamada();
        
          
        mostrarLlamadas();
       }
    }//GEN-LAST:event_jButtonRegistraLlamadaActionPerformed

    private void jButtonSaveTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveTelActionPerformed
        //Guarda tel contacto y email
        
        if(jTextFieldTelefono.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Campos requeridos: Telefono");
        }
        else{
            anadirTelefono();
            limpiarCajas();
            mostrarDatos();
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonSaveTelActionPerformed

    private void jTableLlamadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLlamadasMouseClicked
        // Abre jdialog frame y mostra detalle llamada
        
        if (evt.getClickCount()==2){
        VisualizaLlamadas visualiza = new VisualizaLlamadas(this,true);
        
        
              
        
        int filaSeleccionada1=jTableLlamadas.rowAtPoint(evt.getPoint());
        visualiza.jLabelUsuario.setText(jTableLlamadas.getValueAt(filaSeleccionada1, 5).toString());
        visualiza.jLabelTipoLlamada.setText(jTableLlamadas.getValueAt(filaSeleccionada1, 1).toString());
        visualiza.jLabelFecha.setText(jTableLlamadas.getValueAt(filaSeleccionada1, 3).toString());
        visualiza.jLabelHora.setText(jTableLlamadas.getValueAt(filaSeleccionada1, 4).toString());
        visualiza.jTextArea1.setText(jTableLlamadas.getValueAt(filaSeleccionada1, 2).toString());
        visualiza.jLabelId.setText(jTableLlamadas.getValueAt(filaSeleccionada1, 0).toString());
        //visualiza.codCliente=jTextFieldCodCliente.getText();
        
        
        visualiza.setLocationRelativeTo(this);
        visualiza.setVisible(true);
        
        
        
      
        }  
        
    }//GEN-LAST:event_jTableLlamadasMouseClicked

    private void jTableLlamadasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableLlamadasFocusGained
       mostrarLlamadas();
    }//GEN-LAST:event_jTableLlamadasFocusGained
    
    
    
    
   ///=============================================================metodos  Rodrigo
    
        public void filtrarDatos(String valor){
            
        
        
        String [] titulos= {"cod Cliente","Nombre", "Nombre_Comercial", "Telefono", "Contacto", "Email"};
        String [] registros= new String[6];
        DefaultTableModel modelo= new DefaultTableModel(null, titulos);
        
        //String SQL="SELECT * FROM clientes WHERE nombre LIKE '%"+valor+"%'" /*OR nombre_comercial LIKE '%"+valor+"%'" */;
        String SQL="SELECT clientes.cod_cliente, clientes.nombre, clientes.nombre_comercial, telefonos.telefono, telefonos.contacto_tel, telefonos.email FROM clientes LEFT JOIN telefonos ON clientes.cod_cliente = telefonos.cod_cliente_tel "
                + "WHERE nombre LIKE '%"+valor+"%' OR telefono LIKE '%"+valor+"%' OR email LIKE '%"+valor+"%' ";
        try {
            
            Statement st= con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){
                
                registros [0]=rs.getString("clientes.cod_cliente");
                registros [1]=rs.getString("clientes.nombre");
                registros [2]=rs.getString("clientes.nombre_comercial");
                registros [3]=rs.getString("telefonos.telefono");
                registros [4]=rs.getString("telefonos.contacto_tel");
                registros [5]=rs.getString("telefonos.email");
                
                modelo.addRow(registros);
            
            }
            
            jTableClientes.setModel(modelo);
            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"no se ha podido subir los datos" + e.getMessage());
        }
        }
    
    
        public void eliminarRegistros(){
            
            
            
            int filaSeleccionada=jTableClientes.getSelectedRow();
            
            try {
                String SQL= "DELETE FROM clientes WHERE cod_cliente= "+"\""+jTableClientes.getValueAt(filaSeleccionada, 0)+"\"" ;
                Statement st= con.createStatement();
                
                int n=st.executeUpdate(SQL);
                
                if(n>=0){
                    JOptionPane.showMessageDialog(null,"Registro Eliminado!");
                    
                }
                
            } catch (Exception e) {
                  JOptionPane.showMessageDialog(null,"Error al eliminar Registro!" + e.getMessage());
                
            }
        
        
        }
        
    
    
        public void actualizarDatos(String codigo){
          
        
        try {
            Cliente actCliente = new Cliente(jTextFieldCodCliente.getText(),jTextFieldNombre.getText(), jTextFieldNombreComercial.getText());
            
            String SQL= "update clientes set cod_cliente=?, nombre=?, nombre_comercial=?where cod_cliente=?" ;
            
            
           int filaSeleccionada=jTableClientes.getSelectedRow();
           String dao=(String)jTableClientes.getValueAt(filaSeleccionada, 0);
            
            PreparedStatement pst=con.prepareStatement(SQL);
            
            pst.setString(1, actCliente.getCodCliente());
            pst.setString(2, actCliente.getNombre());
            pst.setString(3, actCliente.getNombreComercial());
            //pst.setString(4, actCliente.getContacto());
            
            pst.setString(4, dao);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Registrado Actualizado");
            
            
          
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,"Error actualizar registro" + e.getMessage());
        }
        }
        
        public void actualizarTelefono(){
        
        try {
                 
           
            
              ///ACTUALIZAR TELEFONO
          Telefonos actTelefono = new Telefonos(jTextFieldCodCliente.getText(), jTextFieldTelefono.getText(), jTextFieldContacto.getText(), jTextFieldEmail.getText());
            
            String SQL2= "update telefonos set telefono=?, contacto_tel=?, email=? where telefono=? and cod_cliente_tel=?" ;
            
            int filaSeleccionada=jTableClientes.getSelectedRow();
           String dao=(String)jTableClientes.getValueAt(filaSeleccionada, 3);
           String dao2=(String)jTableClientes.getValueAt(filaSeleccionada, 0);
            
            PreparedStatement pst=con.prepareStatement(SQL2);
            pst.setString(1, actTelefono.getTelefono());
            pst.setString(2, actTelefono.getContactoTel());
            pst.setString(3, actTelefono.getEmail());
            
            pst.setString(4, dao);
            pst.setString(5, dao2);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Registrado telefono Actualizado");
            
            
          
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error actualizar registro " + e.getMessage());
        }
        
        
    
    }
    
    public void mostrarDatos(){
        String [] titulos= {"cod Cliente","Nombre", "Nombre_Comercial", "Telefono","Contacto", "Email"};
        String [] registros= new String[6];
        DefaultTableModel modelo= new DefaultTableModel(null, titulos);
        
        String SQL="SELECT clientes.cod_cliente, clientes.nombre, clientes.nombre_comercial, telefonos.telefono, telefonos.contacto_tel, telefonos.email FROM clientes LEFT JOIN telefonos ON clientes.cod_cliente = telefonos.cod_cliente_tel";
        
        try {
            
            Statement st= con.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            
            while (rs.next()){
                
                registros [0]=rs.getString("cod_cliente");
                registros [1]=rs.getString("nombre");
                registros [2]=rs.getString("nombre_comercial");
                registros [3]=rs.getString("telefono");
                registros [4]=rs.getString("contacto_tel");
                registros [5]=rs.getString("email");
                
                modelo.addRow(registros);
            
            }
            
            jTableClientes.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"no se ha podido subir los datos" + e.getMessage());
        }
        
    
    }
    
    public void limpiarCajas(){
        
          jTextFieldBusqueda.setText("");
          jTextFieldCodCliente.setText("");
          jTextFieldNombre.setText("");
          jTextFieldNombreComercial.setText("");
          jTextFieldTelefono.setText("");
          jTextFieldContacto.setText("");
          jTextFieldEmail.setText("");
          jTextAreaComentarios.setText("");
          //cambia color iniciales
          jTextFieldTelefono.setBackground(Color.white);
          jTextFieldContacto.setBackground(Color.white);
          jTextFieldEmail.setBackground(Color.white);
          //Config inicla botones
          jButtonNuevo.setVisible(true);
          jButtonGuardar.setVisible(true);
          jButtonEliminar.setVisible(true);
          jButtonActualizar.setVisible(true);
          jButtonaAnadirTelefono.setVisible(true);
          jButtonSaveTel.setVisible(false);
          jButtonRegistraLlamada.setVisible(true);
          
          
          
        
    }
    
    public void limpiarCajasTelefono(){
          
          jTextFieldTelefono.setText("");
          jTextFieldContacto.setText("");
          jTextFieldEmail.setText("");
          //cambia color
          jTextFieldTelefono.setBackground(Color.yellow);
          jTextFieldContacto.setBackground(Color.yellow);
          jTextFieldEmail.setBackground(Color.YELLOW);
          ///habilita el boton añadir tel y oculta el resto
          
          jButtonNuevo.setVisible(true);
          jButtonGuardar.setVisible(false);
          jButtonEliminar.setVisible(false);
          jButtonActualizar.setVisible(false);
          jButtonaAnadirTelefono.setVisible(false);
          jButtonSaveTel.setVisible(true);
          jButtonRegistraLlamada.setVisible(false);
        
    }
    
    
    public void insertarDatos(){
        
       
        try {
            Cliente cliente = new Cliente(jTextFieldCodCliente.getText(),jTextFieldNombre.getText(), jTextFieldNombreComercial.getText());
            String SQL= "insert into clientes (cod_cliente, nombre, nombre_comercial) values(?,?,?)";
            
            
            
            PreparedStatement pst=con.prepareStatement(SQL);
            
            pst.setString(1, cliente.getCodCliente());
            pst.setString(2, cliente.getNombre());
            pst.setString(3, cliente.getNombreComercial());
            
            
            
            
            pst.execute();
            JOptionPane.showMessageDialog(this,"Registrado contacto Correcto");
                    
                  
                        
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error registro" + e.getMessage());
        }
        
       
    
    }
    
    public void anadirTelefono(){
        
       
        try {
            Telefonos telefono = new Telefonos(jTextFieldCodCliente.getText(),jTextFieldTelefono.getText(), jTextFieldContacto.getText(), jTextFieldEmail.getText());
            String SQL= "insert into telefonos (cod_cliente_tel, telefono, contacto_tel, email) values(?,?,?,?)";
            
            
            
            PreparedStatement pst=con.prepareStatement(SQL);
            
            pst.setString(1, telefono.getCod_cliente_Tel());
            pst.setString(2, telefono.getTelefono());
            pst.setString(3, telefono.getContactoTel());
            pst.setString(4, telefono.getEmail());
            
            
            
            
            
            pst.execute();
            JOptionPane.showMessageDialog(this,"Telefono Registrado Correctamente");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error registro telefono" + e.getMessage());
        }
        
        
    
    }
    
    //===========================================================================
    ///funciones registro llamada
    public void registroLlamada(){
        
        try {
            Incidencias incidencia = new Incidencias(jTextFieldCodCliente.getText(),jComboBoxTipoLlamada.getSelectedItem().toString(),jTextAreaComentarios.getText(), jLabelUsuario.getText());
            
            String SQL= "insert into registro_llamada (cod_cliente_llamada, tipo_llamada, comentarios, usuario) values(?,?,?,?)";
            
             PreparedStatement pst=con.prepareStatement(SQL);
            
            pst.setString(1, incidencia.getCod_Cliente_llamada());
            pst.setString(2, incidencia.getTipoLlamada());
            pst.setString(3, incidencia.getComentarios());
            pst.setString(4, incidencia.getUsuario());
            
            
            
            
            
            
            pst.execute();
            JOptionPane.showMessageDialog(this,"Registo Correcto");
            
            
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(this,"Error registro, incidencias" + e.getMessage());
        }
        
        jTextAreaComentarios.setText("");
        
    }
    
    
    
    public void mostrarLlamadas(){
        String [] titulosLlamada= {"id_Llamada","Tipo_Llamada", "Comentarios", "Fecha", "Hora", "Usuario"};
        String [] registrosLlamadas= new String[6];
        DefaultTableModel modeloLlamada= new DefaultTableModel(null, titulosLlamada);
        
        String SQL="SELECT registro_llamada.id_llamada, registro_llamada.tipo_llamada, registro_llamada.comentarios, registro_llamada.fecha, registro_llamada.hora, registro_llamada.usuario"
                + "  FROM registro_llamada WHERE registro_llamada.cod_cliente_llamada= '"+jTextFieldCodCliente.getText()+"' ORDER BY registro_llamada.fecha DESC, registro_llamada.hora  DESC";
        
        try {
            
            Statement st= con.createStatement();
            ResultSet rsLlamada=st.executeQuery(SQL);
            
            while (rsLlamada.next()){
                
                registrosLlamadas [0]=rsLlamada.getString("id_Llamada");
                registrosLlamadas [1]=rsLlamada.getString("Tipo_Llamada");
                registrosLlamadas [2]=rsLlamada.getString("Comentarios");
                registrosLlamadas [3]=rsLlamada.getString("Fecha");
                registrosLlamadas [4]=rsLlamada.getString("Hora");
                registrosLlamadas [5]=rsLlamada.getString("Usuario");
                
                
                modeloLlamada.addRow(registrosLlamadas);
            
            }
            
            jTableLlamadas.setModel(modeloLlamada);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"no se ha podido subir los datos de llamadas" + e.getMessage());
        }
        
    
    }
    
    
    
    
    
    //==========================================================================
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonRegistraLlamada;
    private javax.swing.JButton jButtonSaveTel;
    private javax.swing.JButton jButtonaAnadirTelefono;
    private javax.swing.JComboBox<String> jComboBoxTipoLlamada;
    private javax.swing.JLabel jLabelBusqueda;
    private javax.swing.JLabel jLabelCodCliente;
    private javax.swing.JLabel jLabelComentarios;
    private javax.swing.JLabel jLabelContacto;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreCom;
    private javax.swing.JLabel jLabelTeamBike;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoLlamada;
    private javax.swing.JLabel jLabelTitulo;
    public static javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableLlamadas;
    private javax.swing.JTextArea jTextAreaComentarios;
    private javax.swing.JTextField jTextFieldBusqueda;
    public static javax.swing.JTextField jTextFieldCodCliente;
    private javax.swing.JTextField jTextFieldContacto;
    private javax.swing.JTextField jTextFieldEmail;
    public static javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreComercial;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
